development:
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: linkmercado

test:
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: linkmercado_teste

production:
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: linkmercado
